services:
  content.entity.mamager:
    class: CoreBundle\Plugins\Entity\ContentEntityManager
    arguments: ['@schema_reader']

  schema_reader:
    class: CoreBundle\Plugins\Utils\SchemaReader
    arguments: ['@kernel']